# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Show jj after git but before rest of prompts
format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$fossil_metrics\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
${custom.jj_change}\
${custom.jj_empty}\
${custom.jj_desc}\
$all"""

right_format = """$shell"""

command_timeout = 750

# Replace the 'â¯' symbol in the prompt with 'âžœ'
# [character] # The name of the module we are configuring is 'character'
# success_symbol = '[âžœ](bold green)' # The 'success_symbol' segment is being set to 'âžœ' with the color 'bold green'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[git_commit] # Hide the git commit prompt
disabled = true

[custom.sf]
description     = "The target org used by default for Salesforce CLI commands"
command         = ''' sf config get target-org --json | from json | get result.value.0 '''
when            = ''' sf config get target-org --json | from json | get result.value '''
format          = 'via [$symbol ($output)]($style) '
style           = 'bold 039'
symbol          = 'ó°¢Ž'
ignore_timeout  = true

[custom.jj_change]
description     = "The working copy of the repo in your current directory: workspaces (if relevant), change ID, bookmarks"
command         = ''' jj log --no-graph -r=@ -T='separate(" ", working_copies, change_id.shortest(), bookmarks,)' '''
when            = ''' zsh -c 'test -n "$(jj status)" || exit 1' '''
format          = 'on [$symbol ($output)]($style) '
symbol          = 'ðŸ¦'
style           = 'bold purple'
ignore_timeout  = true

[custom.jj_empty]
description     = "Shows (empty) in green if the working copy has no changes"
command         = ''' echo "(empty)" '''
when            = ''' zsh -c 'test -n "$(jj status)" -a -z "$(jj diff -s -r=@)" || exit 1' '''
format          = '[$output]($style) '
style           = 'bold green'
ignore_timeout  = true

[custom.jj_desc]
description     = "The description of your working copy, if set"
# command         = ''' jj log --no-graph -r=@ -T="description.first_line()" | awk '{if(length($0) > 25) {s = substr($0, 1, 25); sub(/[ \t\r\n]+$/, "", s); print s "â€¦"} else {print $0}}' '''
command         = ''' jj log --no-graph -r=@ -T='if(description, description.first_line(), "(no description)")' '''
when            = ''' zsh -c 'test -n "$(jj status)" || exit 1' '''
format          = '$symbol [($output)]($style) '
symbol          = '|'
ignore_timeout  = true

[shell]
disabled = false
format = '[$indicator]($style) '
